spring.application.name=Movies

# 接続先DBのURL（localhost:5432 の後にDB名を入力してください）
spring.datasource.url=jdbc:postgresql://localhost:5432/movies_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
server.port = 8090


# Hibernateの設定（SQLログの表示など）
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# 保存先のパス（ご自身のPCの適当なフォルダを指定してください）
# 例: Macの場合 /Users/ユーザー名/Documents/uploads/
upload.path=/Users/matsuishuta/uploads/

logging.level.org.springframework.security=ERROR